service: nestjs-cart-service

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs14.x

#you can define service wide environment variables here
environment:
  PG_HOST: ${env:PG_HOST}
  PG_PORT: ${env:PG_PORT}
  PG_DATABASE: ${env:PG_DATABASE}
  PG_USERNAME: ${env:PG_USERNAME}
  PG_PASSWORD: ${env:PG_PASSWORD}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
